### PR TITLE
Cleanup docs

### PR DESCRIPTION
**Pull request by dkg**

### CODE REVIEW

**Comment by rockdaboot** [comment]
Thanks for your contribution. Could you make the pull requests basing on branch 'develop' ?
#49 and #50 somehow conflict when merging / applying manually to develop.

**Comment by dkg** [comment]
Hi Tim--

On Tue 2016-07-05 16:05:05 -0400, Tim Rühsen wrote:
> Thanks for your contribution. Could you make the pull requests basing on branch 'develop' ?
> #49 and #50 somehow conflict when merging / applying manually to develop.

it looks like these commits conflict because one of the publix lines is
right next to one of the https lines.

I've just pushed my cleanup-docs branch atop my http-no-more branch and
manually resolved the overlap.

afaict, 'develop' and 'master' are branches touching the same commit,
right?  If you merge from my cleanup-docs branch it should end up
importing them both.  So something like the below should work:

    git remote add dkg https://github.com/dkg/libpsl
    git remote update dkg
    git checkout develop
    git merge --ff-only dkg/cleanup-docs

hth,

        --dkg

**Comment by rockdaboot** [comment]
Merging cleanup-docs now works, thanks.
Just a question before I push your changes... You didn't use line breaks (.br) in psl.1, that looks a bit unformatted. Purpose or accidentially ?

**Comment by rockdaboot** [comment]
And another one... ABOUT-NLS will be regenerated by autoreconf -fi. Changes it will be automatically overwritten at some point.

**Comment by dkg** [comment]
On Wed 2016-07-06 06:04:36 -0400, Tim Rühsen wrote:
> Merging cleanup-docs now works, thanks.
> Just a question before I push your changes... You didn't use line breaks (.br) in psl.1, that looks a bit unformatted. Purpose or accidentially ?

my nroff skills are mostly cargo-cult, and this one started out from the
spare output of help2man.  If you've got improvements that would make
the documentation seem easier to edit and maintain going forward, or
just to make it easier to read, there's no objection from my side.

     --dkg

**Comment by dkg** [comment]
On Wed 2016-07-06 07:01:51 -0400, Tim Rühsen wrote:
> And another one... ABOUT-NLS will be regenerated by autoreconf -fi. Changes it will be automatically overwritten at some point.

good point.  I'd be happy to see all generated files removed from the
git repo.  If someone is building from git, they should be able to
autoreconf on their own, right?

           --dkg

**Comment by rockdaboot** [comment]
There are several markdown to man page tools, none of that satisfied me until now. Either broken, no docs, no examples, not installable, ... sigh
For big players like Doxygen, GTK-DOC, sphinx, texinfo, ... you need too much time to work into - and they all have their huge downsides (and bugs !).
Documentation for software/APIs is not an easy go.

But back to business ;-) Merged, psl.1 amended, ABOUT-NLS removed from repo, psl link step cleaned up.

**Comment by rockdaboot** [comment]
@dkg Found a working markdown to manpage converter: https://github.com/sunaku/md2man

**Comment by dkg** [comment]
On Thu 2016-07-07 10:08:56 -0400, Tim Rühsen wrote:
> @dkg Found a working markdown to manpage converter: https://github.com/sunaku/md2man

hm, if this is part of the build process, it'd be nicer for me as a
packager to use one that's already in debian.  are you unhappy with
pandoc's output?

         --dkg

**Comment by rockdaboot** [comment]
The last time I tried pandoc, something didn't work, but that is really a long time ago.
A man page looks like a man page, doesn't it ? If pandoc does the job, it's absolutely fine.

**Pull request closed without merging**
