### PR TITLE
Implement is_ip4() and is_ip6() to avoid network dependencies

### LINKED ISSUE #226: Replace `isip()` code with the free code from Paul Vixie
This would allow to drop a runtime dependency on Windows.

The code is e.g. at https://opensource.apple.com/source/xnu/xnu-4903.221.2/libkern/net/inet_pton.c.auto.html

We can simplify or throw out parts of it as we are only interested in a boolean return value.

### PR DESCRIPTION
**Pull request by rockdaboot**
Can someone please review, especially try compiling on Windows?

Fixes #226

### CODE REVIEW

**Comment by eli-schwartz** [comment]
@rockdaboot I tested it in the meson CI matrix:
- Your patch compiles fine with Visual Studio: https://github.com/mesonbuild/wrapdb/actions/runs/7599023779/job/20695630342
- Your patch + removing ws2_32 in meson.build as well, FAILS to compile: https://github.com/mesonbuild/wrapdb/actions/runs/7599032955/job/20695724242 "unresolved external symbol __imp_WSAStartup referenced in function main"
- With Msys2 + clang, it fails due to GetACP being undefined.

There are some additional problems in these logs, which are unelated to your change (i.e. problems with stock 0.21.5). @neheb probably should look into that, having expressed interest before:
- With clang-cl: test-is-cookie-domain-acceptable.c fails to compile, alloca() is not made available
- With Msys2 and either gcc or clang it compiles, some tests fail

**Comment by neheb** [comment]
Why avoid network dependencies?

**Comment by vszakats** [comment]
> > With Msys2 + clang, it fails due to GetACP being undefined.
> 
> That has been my fear. GetACP() requires Windows.h (see https://learn.microsoft.com/en-us/windows/win32/api/winnls/nf-winnls-getacp).
> 
> > "unresolved external symbol __imp_WSAStartup referenced in function main"
> 
> Maybe we can get rid of that. Not sure if GetACP() needs it.

`GetACP()` doesn't need it:
https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/localtime-s-localtime32-s-localtime64-s?view=msvc-170

`windows.h` is only required with libidn2 or libidn, of which libidn2 already
requires it, so it's okay. Haven't checked libidn. Either way it's safe to 
assume that `windows.h` is available when `_WIN32` is set by the compiler.

Here's a patch that may help (I've only given it a limited build test):
```diff
diff --git a/src/psl.c b/src/psl.c
index 0168a68..aa3caeb 100644
--- a/src/psl.c
+++ b/src/psl.c
@@ -47,6 +47,11 @@
 #include <sys/types.h>
 #include <sys/stat.h>
 
+#if defined(_WIN32) && (defined(WITH_LIBIDN2) || defined(WITH_LIBIDN))
+# define WIN32_LEAN_AND_MEAN
+# include <windows.h> /* for GetACP() */
+#endif
+
 #if defined(_MSC_VER) && ! defined(ssize_t)
 # include <basetsd.h>
 typedef SSIZE_T ssize_t;
diff --git a/tests/test-is-cookie-domain-acceptable.c b/tests/test-is-cookie-domain-acceptable.c
index d58bd47..17b46c6 100644
--- a/tests/test-is-cookie-domain-acceptable.c
+++ b/tests/test-is-cookie-domain-acceptable.c
@@ -32,10 +32,6 @@
 # include <config.h>
 #endif
 
-#ifdef _WIN32
-# include <winsock2.h> // WSAStartup, WSACleanup
-#endif
-
 #include <stdio.h>
 #include <stdlib.h>
 #include <string.h>
@@ -113,18 +109,6 @@ static void test_psl(void)
 
 int main(int argc, const char * const *argv)
 {
-#ifdef _WIN32
-	WSADATA wsa_data;
-	int err;
-
-	if ((err = WSAStartup(MAKEWORD(2,2), &wsa_data))) {
-		printf("WSAStartup failed with error: %d\n", err);
-		return 1;
-	}
-
-	atexit((void (__cdecl*)(void)) WSACleanup);
-#endif
-
 	/* if VALGRIND testing is enabled, we have to call ourselves with valgrind checking */
 	if (argc == 1) {
 		const char *valgrind = getenv("TESTS_VALGRIND");
diff --git a/tools/psl.c b/tools/psl.c
index 527d780..7ffd9d7 100644
--- a/tools/psl.c
+++ b/tools/psl.c
@@ -37,8 +37,7 @@
 #endif
 
 #ifdef _WIN32
-# include <winsock2.h> // WSAStartup, WSACleanup
-
+# include <time.h>
 // Windows does not have localtime_r but has localtime_s, which is more or less
 // the same except that the arguments are reversed
 # define LOCALTIME_R_SUCCESSFUL(t_sec,t_now)	\
@@ -78,20 +77,6 @@ static void usage(int err, FILE* f)
 	exit(err);
 }
 
-static void init_windows(void) {
-#ifdef _WIN32
-	WSADATA wsa_data;
-	int err;
-
-	if ((err = WSAStartup(MAKEWORD(2,2), &wsa_data))) {
-		printf("WSAStartup failed with error: %d\n", err);
-		exit(EXIT_FAILURE);
-	}
-
-	atexit((void (__cdecl*)(void)) WSACleanup);
-#endif
-}
-
 /* RFC 2822-compliant date format */
 static const char *time2str(time_t t)
 {
@@ -238,8 +223,6 @@ int main(int argc, const char *const *argv)
 				else if (mode == 4) {
 					char *cookie_domain_lower;
 
-					init_windows();
-
 					if ((rc = psl_str_to_utf8lower(domain, NULL, NULL, &cookie_domain_lower)) == PSL_SUCCESS) {
 						if (!batch_mode)
 							printf("%s: ", domain);
@@ -284,8 +267,6 @@ int main(int argc, const char *const *argv)
 		}
 	}
 	else if (mode == 4) {
-		init_windows();
-
 		for (; arg < argv + argc; arg++) {
 			if (!batch_mode)
 				printf("%s: ", *arg);
```

**Comment by rockdaboot** [comment]
Thank you @vszakats !

@eli-schwartz Pushed the removal of WSA code. When #231 is merged, I'll rebase this PR and ping you for another round of tests.

**Comment by eli-schwartz** [comment]
It works with msys2 and GCC, but fails with msys2 and clang:

```
3/8 test-is-cookie-domain-acceptable FAIL            0.03s   exit status 1
>>> ASAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1 MALLOC_PERTURB_=90 UBSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 PATH=D:/a/_temp/msys64/clang64/bin;D:/a/wrapdb/wrapdb/_build/subprojects/libpsl-0.21.5/src;D:\a\_temp\msys64\clang64\bin;D:\a\_temp\msys64\usr\local\bin;D:\a\_temp\msys64\usr\bin;D:\a\_temp\msys64\usr\bin;C:\Windows\System32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;D:\a\_temp\msys64\usr\bin\site_perl;D:\a\_temp\msys64\usr\bin\vendor_perl;D:\a\_temp\msys64\usr\bin\core_perl D:/a/wrapdb/wrapdb/_build/subprojects/libpsl-0.21.5/tests/test-is-cookie-domain-acceptable.exe
------------------------------------- 8< -------------------------------------
loaded 9556 suffixes and 8 exceptions

psl_is_cookie_domain_acceptable(192.1.123.2, .1.123.2)=1 (expected 0)

psl_is_cookie_domain_acceptable(::ffff:192.1.123.2, .1.123.2)=1 (expected 0)

Summary: 2 out of 23 tests failed

[...]

Summary of Failures:

3/8 test-is-cookie-domain-acceptable FAIL            0.03s   exit status 1

Ok:                 4   
Expected Fail:      0   
Fail:               1   
Unexpected Pass:    0   
Skipped:            3   
Timeout:            0   
```

**Comment by rockdaboot** [comment]
@eli-schwartz Just to make sure, without the new `is_ip` functions, does the test succeed?

Because if the first parameter to `psl_is_cookie_domain_acceptable()` is an IP address, the function returns 0. Getting a 1 here means, that check failed. And the is_ip checks are pure string/memory operations, I don't see anything there that isn't portable.

**Comment by eli-schwartz** [comment]
It's being run against the 0.21.5 release with:
- [libpsl-no-alloca.patch](https://github.com/mesonbuild/wrapdb/blob/libpsl/subprojects/packagefiles/libpsl-no-alloca.patch) (backport of #231) applied
  - which passes here: https://github.com/mesonbuild/wrapdb/actions/runs/7859202656/job/21445032024
- [libpsl-winipv4.patch](https://github.com/mesonbuild/wrapdb/blob/libpsl/subprojects/packagefiles/libpsl-winipv4.patch), [libpsl-winipv4-meson.patch](https://github.com/mesonbuild/wrapdb/blob/libpsl/subprojects/packagefiles/libpsl-winipv4-meson.patch) applied, the first being this PR, the second being my adaptation of the meson files
  - which fails here: https://github.com/mesonbuild/wrapdb/actions/runs/7863678837/job/21454561767

**Comment by rockdaboot** [comment]
The reason for the fuzz tests not building is likely a missing DLL (need to be added to LDADD in fuzz/Makefile.am), but can't test that anyway. With MinGW on Linux, it's not a problem (fuzz tests are SKIPped). Added `contrib/mingw.static` to cross-build the library, tool and tests.

**Pull request merged**
