### PR TITLE
meson: install the library

### PR DESCRIPTION
**Pull request by nacho**
SSIA

### CODE REVIEW

**Comment by xclaesse** [comment]
You probably also want to install headers, using `install_headers()` function. Are there other files that needs to be installed? I haven't looked at the part when doing the port, I'm using it uninstalled myself.

**Comment by nacho** [comment]
@xclaesse I guess we need it installed for libsoup?

**Comment by nacho** [comment]
@xclaesse done

**Comment by xclaesse** [comment]
@nacho Now that I think about it, I'm surprised it works for me actually. Looks like that when I do `ninja install` in libsoup and libpsl is built as subproject, meson is smart enough to detect that libpsl.so is needed and it install it even without `install: true`. I just checked and when libpsl is built as standalone, libpsl.so is not installed, so this patch is needed.

**Comment by xclaesse** [comment]
@nacho I haven't checked if autotools install other files as well, but this is at least a good start, LGTM.

**Comment by rockdaboot** [comment]
merged manually

**Pull request closed without merging**
