### PR TITLE
Libidn flags

### PR DESCRIPTION
**Pull request by dago**
The linkage should use the correctly discovered LIBIDN_LIBS and LIBIDN2_LIBS

### CODE REVIEW

**Comment by rockdaboot** [comment]
Hi Dago :-)

did you test this locally ?

From Travis CI:

make[3]: Entering directory `/home/travis/build/rockdaboot/libpsl/libpsl-0.19.1/_build/tools'
  CC       psl.o
  CCLD     psl
../src/.libs/libpsl.so: undefined reference to `idn2_lookup_u8'
../src/.libs/libpsl.so: undefined reference to `u8_tolower'
../src/.libs/libpsl.so: undefined reference to `u8_strlen'
../src/.libs/libpsl.so: undefined reference to `uninorm_nfkc'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [psl] Error 1

**Comment by dago** [comment]
Yes, I tested this locally. I would guess that pkgconfig-files are broken again for libidn and/or libidn2.

**Comment by rockdaboot** [comment]
If I had the time I would move to Gitlab and use my own CI runners there. Travis is so behind...

Not sure what to do now (and not much time for testing).

**Comment by dago** [comment]
You can essentially connect your own runners to GitLab e.g. with buildbot. This is what I had configured - but the hard part is feeding back the results to different projects with different tokens, this is also I took down my Solaris CI service for now until this is fixed.

**Comment by dago** [comment]
@rockdaboot I now readded the unconditional linkage against libunistring.so and it still failes in Travis. Do you have an idea what is going on here?

**Comment by rockdaboot** [comment]
Hi @dago. Your master branch is far behind the current master. You should just rebase your changes and push -f.

**Pull request closed without merging**
