### PR TITLE
Make code buildable on native Windows (Win32)

### PR DESCRIPTION
**Pull request by fanc999**
Hi,

As GNOME's libsoup, which is supported on Windows natively, now depends on the libpsl library, I am proposing some simple changes to the code so that libpsl can build and run on Windows without the need for Cygwin, and so that libsoup will continue to work natively on Windows.

I will also (possibly in another PR) contribute a set of NMake Makefiles to build libpsl under Visual Studio.

With blessings, thank you!

### CODE REVIEW

**Comment by rockdaboot** [comment]
Hi, thanks for your contribution !

A question regarding the decorator, shouldn't it look more like the following ? Can you test that on Windows ?
```
// see https://www.gnu.org/software/gnulib/manual/html_node/Exported-Symbols-of-Shared-Libraries.html
#if HAVE_VISIBILITY
#       define PSL_API __attribute__ ((__visibility__("default")))
#elif defined _MSC_VER && !defined PSL_STATIC
#       define PSL_API __declspec(dllexport)
#elif defined _MSC_VER && !defined PSL_STATIC
#       define PSL_API __declspec(dllimport)
#else
#       define PSL_API
#endif
```

**Comment by fanc999** [comment]
Hi @rockdaboot,

It could, but this was done this way so that we could define that as a CFLAG or a config.h variable during the build of the library.  This essentially follows the pattern of what is now done in libsoup, GLib and so, in GNOME, albeit that I didn't define that as "extern" by default.  We could probably then use some autotools (or so) definition, like what is done in GLib to define PSL_API accordingly in config.h, which will do what is needed during the build of libpsl.

The above would probably not be enough for _MSC_VER because there needs to be a distinction when we are building libpsl and when we are using libpsl (for instance, we need to have a CFLAG that says something like -DPSL_COMPILATION or so when we are building libpsl to use __declspec(dllexport)).

Let me know which way is preferable though, so that I can make the necessary changes, if needed.

With blessings, thank you!

**Comment by rockdaboot** [comment]
Is this more appropriate ? I'd prefer something like this, having other projects in mind. If you need (only if), we could also have a `#ifdef PSL_API` around it.
```
#if defined BUILDING_PSL && HAVE_VISIBILITY
#       define PSL_API __attribute__ ((__visibility__("default")))
#elif defined BUILDING_PSL && defined _MSC_VER && !defined PSL_STATIC
#       define PSL_API __declspec(dllexport)
#elif defined _MSC_VER && !defined PSL_STATIC
#       define PSL_API __declspec(dllimport)
#else
#       define PSL_API
#endif
```

**Comment by rockdaboot** [comment]
@fanc999 I merged your code manually and added another commit to extend and rename the decorator to PSL_API. Please check if that works for you now.

**Pull request closed without merging**
