### PR TITLE
Make the generated public suffix list constexpr

### PR DESCRIPTION
**Pull request by wangwenx190**

### CODE REVIEW

**Comment by wangwenx190** [comment]
ping?

**Comment by rockdaboot** [comment]
@wangwenx190 Sorry for the delay, I somehow missed this PR.

`constexpr` is C++, while this tool is needed to create C compatible code for libpsl. I see the comment above is misleading. What about changing it from `C++` to `C` ?

**Comment by wangwenx190** [comment]
> @wangwenx190 Sorry for the delay, I somehow missed this PR.
> 
> `constexpr` is C++, while this tool is needed to create C compatible code for libpsl. I see the comment above is misleading. What about changing it from `C++` to `C` ?

Can I read it as "the comments are wrong and need to be corrected, this PR is no more needed"?

**Comment by rockdaboot** [comment]
> > @wangwenx190 Sorry for the delay, I somehow missed this PR.
> > `constexpr` is C++, while this tool is needed to create C compatible code for libpsl. I see the comment above is misleading. What about changing it from `C++` to `C` ?
> 
> Can I read it as "the comments are wrong and need to be corrected, this PR is no more needed"?

Yes.
The library code is C89.

**Comment by wangwenx190** [comment]
OK, thanks for your reply! I'll close this PR then.

**Comment by rockdaboot** [comment]
Thanks for bringign this up and sorry for your spent time.
I just pushed a fix for the comments (using C/C++ instead of C++).

**Comment by wangwenx190** [comment]
It doesn't matter, no need to apologize. :)

**Pull request closed without merging**
