### PR TITLE
Meson: Fix srcdir pointing to root source dir instead of current subdir

### PR DESCRIPTION
**Pull request by xclaesse**
With that fuzz tests seems to be doing a lot more work.

### CODE REVIEW

**Comment by rockdaboot** [comment]
Looks good :-) Thank you.

Next questions ;-)
- how to make an ASAN / UBSAN build ?
- how to run the tests using valgrind ?

Nothing urgent, but to use meson in a Travis CI runner, potentially replacing autotools at some point.

**Comment by xclaesse** [comment]
>     * how to make an ASAN / UBSAN build ?

Meson has built-in support for that, you can configure with `meson -Db_sanitize=<value> builddir` where value is one of [none, address, thread, undefined, memory, address,undefined]. Does that cover all you need? To verify you can check the flags passed to the compiler by running `ninja -C builddir -v` to print command lines executed.

>     * how to run the tests using valgrind ?

Tests can be run with `meson test --wrap='valgrind --tool=memcheck'`. See http://mesonbuild.com/Unit-tests.html.

Is that enough for your needs?

**Comment by rockdaboot** [comment]
Perfect, thanks for the info.

**Comment by rockdaboot** [comment]
I fail to build with meson+ASAN+clang. Ubsan and valgrind seems to succeed, also everything succeeds when building with gcc.

If you could have a look into contrib/check-hard-meson if something obvious is missing !? It's a simple shell script, the ASAN part is commented out.

**Comment by xclaesse** [comment]
I don't know anything about ASAN tbh, but I see Meson prints a warning:
```
WARNING: Trying to use undefined sanitizer on Clang with b_lundef.
This will probably not work.
Try setting b_lundef to false instead.
```

Here I get many linker failure liket this one:
```
/home/xclaesse/programmation/libsoup/subprojects/libpsl/builddir/../src/lookup_string_in_fixed_set.c:208: undefined reference to `__ubsan_handle_pointer_overflow'
```

**Comment by xclaesse** [comment]
Note that with Meson we don't usually pass CFLAGS from the env. Better add them in the meson.build definition with `add_project_arguments(cc.get_supported_arguments([...]), language : 'c')`. Also the C std can be set in `project(default_options : ['c_std=gnu89'])`.

But that's details, it should work with CFLAGS too.

**Comment by rockdaboot** [comment]
Looks like the asan build needs `-Db_sanitize=address -Db_lundef=false` *plus* some additional flags for the compiler (both clang and gcc): `-fsanitize=address -fno-omit-frame-pointer -fsanitize-address-use-after-scope`.

**Pull request merged**
