### PR TITLE
Faster, more concurrent travis builds

### PR DESCRIPTION
**Pull request by darnir**

### CODE REVIEW

**Comment by darnir** [comment]
This closes #38

**Comment by rockdaboot** [comment]
Nice !!!
I merged your changes into 'develop' (master is for releases only, please), everything fails for no obvious reason. 'make distcheck' exited with 0. Your build exited with 1.
Any idea ?

**Comment by darnir** [comment]
I'll take a look.

And sorry, I just chose the option GitHub provided for a pull request without seeing.

**Comment by darnir** [comment]
`make check` fails locally for me as well with runtime library disabled.
So I'm assuming it's a bug in the code in this branch.

**Pull request closed without merging**
