### PR TITLE
s/Publix/Public/g

### PR DESCRIPTION
**Pull request by DreaminginCodeZH**

### CODE REVIEW

**Comment by DreaminginCodeZH** [comment]
Note that the project description on GitHub also contained the typo "Publix" that needs a manual fix.

**Comment by daurnimator** [comment]
Note this was already partially fixed by https://github.com/rockdaboot/libpsl/commit/2a3a743643f2bf76fe35baf5692d797a40972891

Also note that old NEWS entries should not be changed

**Comment by DreaminginCodeZH** [comment]
2a3a743 is on master but PRs should be based on develop as I seen in other PRs, so I've replaced all of them. 

There are also some people who think typos can be fixed in NEWS file according to [a quick google search](https://www.google.com/search?q=fix+typo+in+NEWS+file) so I added them; glad to amend if it should be otherwise.

**Comment by DreaminginCodeZH** [comment]
@rockdaboot Opened another PR #75 based on master, closing.

**Pull request closed without merging**
